server:
  port: 8080
spring:
  main:
    banner-mode: off

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false

  datasource:
    url: jdbc:mysql://localhost:3306/bankapp
    username: root
    password: Deil135

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect