server:
  port: 8080
spring:
  main:
    banner-mode: off


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changeset/db.changelog-master.yaml
    drop-first: true

  datasource:
    url: jdbc:mysql://localhost:3306/bankapp
    username: root
    password: Deil135

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect